config/routes.rb
Rails.application.routes.draw do
  get 'partners/new', to: 'home#new', as: 'new_partner'
  post 'partners', to: 'home#create', as: 'create_partner'
  get 'partners/:id', to: 'home#edit', as: 'edit_partner'
  put 'partners/:id', to: 'home#update', as: 'update_partner'
  delete 'partners/:id', to: 'home#destroy', as: 'destroy_partner'

  get 'settings', to: 'home#setting', as: 'settings'
  get 'settings/new', to: 'home#new_setting', as: 'new_setting'
  post 'settings', to: 'home#create_setting', as: 'create_setting'
  get 'settings/:id', to: 'home#edit_setting', as: 'edit_setting'
  put 'settings/:id', to: 'home#update_setting', as: 'update_setting'
  delete 'settings/:id', to: 'home#destroy_setting', as: 'destroy_setting'

  get '/:name', to: 'home#detail', as: 'detail'

  root 'home#index'

end

app/models/partner.rb
class Partner < ActiveRecord::Base
  validates_uniqueness_of :name

  def self.get_all(params)
    all.order(created_at: 'desc').page(params[:page]).per(10)
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validates_uniqueness_of :object_key

  def self.get_all(params)
    all.order(created_at: 'desc').page(params[:page]).per(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def initialize
    super
    @general_service = GeneralService.new
    @partner_service = PartnerService.new
    @setting_service = SettingService.new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_url, only: [:new, :edit]
  before_action :set_url_setting, only: [:new_setting, :edit_setting]
  before_action :get_partner, only: [:edit, :update, :destroy]
  before_action :get_setting, only: [:edit_setting, :update_setting, :destroy_setting]

  def index
    @partners = @partner_service.get_all(params)
    @price_per_click = Setting.find_by(object_key: 'price_per_click').object_value.to_f rescue 1000.to_f
  end

  def new
  end

  def create
    message = @partner_service.create_partner(params)

    redirect_to root_url, message
  end

  def edit
  end

  def update
    message = @partner_service.update_partner(params, @partner)

    redirect_to root_url, message
  end

  def destroy
    message = @partner_service.destroy_partner(@partner)

    redirect_to root_url, message
  end

  def setting
    @settings = @setting_service.get_all(params)
  end

  def new_setting
  end

  def create_setting
    message = @setting_service.create_setting(params)

    redirect_to settings_url, message
  end

  def edit_setting
  end

  def update_setting
    message = @setting_service.update_setting(params, @setting)

    redirect_to settings_url, message
  end

  def destroy_setting
    message = @setting_service.destroy_setting(@setting)

    redirect_to settings_url, message
  end

  def detail
    @general_service.calculate_by_partner(params)
  end

  private
    def set_url
      @url, @method = @general_service.filter_url_and_method(params, '/partners/')
    end

    def set_url_setting
      @url, @method = @general_service.filter_url_and_method(params, '/settings/')
    end

    def get_partner
      @partner = Partner.find(params[:id])
    end

    def get_setting
      @setting = Setting.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def get_total_payment(total_payment)
    total_payment.nil? ? 0 : total_payment
  end

  def get_total_view(total_view)
    total_view.nil? ? 0 : total_view
  end

  def getName(partner)
    partner.nil? ? '' : partner.name
  end

  def getObjectKey(setting)
    setting.nil? ? '' : setting.object_key
  end

  def getObjectValue(setting)
    setting.nil? ? '' : setting.object_value
  end
end

app/views/home/_form.html.erb
<%= form_tag @url, method: @method do %>
  <div class="form-group">
    <label for="exampleInputName">Name</label>
    <input type="text" class="form-control" name="partner[name]" id="exampleInputName" value="<%= getName(@partner) %>" placeholder="Name" required>
  </div>
  <button type="submit" class="btn btn-success">Submit</button>
  <%= link_to "Back", root_path, class: "btn btn-default" %>
<% end %>

app/views/home/_form_setting.html.erb
<%= form_tag @url, method: @method do %>
  <div class="form-group">
    <label for="exampleInputObjectKey">Object Key</label>
    <input type="text" class="form-control" name="setting[object_key]" id="exampleInputObjectKey" value="<%= getObjectKey(@setting) %>" placeholder="Object Key" required>
  </div>
  <div class="form-group">
    <label for="exampleInputObjectValue">Object Value</label>
    <input type="text" class="form-control" name="setting[object_value]" id="exampleInputObjectValue" value="<%= getObjectValue(@setting) %>" placeholder="Object Value" required>
  </div>

  <button type="submit" class="btn btn-success">Submit</button>
  <%= link_to "Back", settings_path, class: "btn btn-default" %>
<% end %>

app/views/home/detail.html.erb
Welcome to ACME.TEST ( <%= params[:partner] %> )

app/views/home/edit.html.erb
<div class="padding50px">
  <h1>Edit Partner</h1>

  <%= render 'form' %>
</div>

app/views/home/edit_setting.html.erb
<div class="padding50px">
  <h1>Edit Setting</h1>

  <%= render 'form_setting' %>
</div>

app/views/home/index.html.erb
<div class="padding50px">
  <%= link_to 'New Partner', new_partner_path, class: 'btn btn-primary' %>
  <%= link_to 'Settings', settings_path, class: 'btn btn-default' %>
  <table class="table margintop20px">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Price Per Click</th>
        <th>Total View</th>
        <th>Total Payment</th>
        <th>Action</th>
    </tr>
    <% @partners.each do |partner| %>
      <tr>
        <td><%= partner.id.to_s %></td>
        <td><%= partner.name %></td>
        <td><%= @price_per_click %></td>
        <td><%= get_total_view(partner.total_view) %></td>
        <td><%= get_total_payment(partner.total_payment) %></td>
        <td><%= link_to 'Edit', edit_partner_path(partner.id) %> | <%= link_to 'Delete', destroy_partner_path(partner.id), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="6" class="center-position"><%= paginate @partners %></td>
    </tr>
  </table>
</div>

app/views/home/new.html.erb
<div class="padding50px">
  <h1>New Partner</h1>

  <%= render 'form' %>
</div>

app/views/home/new_setting.html.erb
<div class="padding50px">
  <h1>New Setting</h1>

  <%= render 'form_setting' %>
</div>

app/views/home/setting.html.erb
<div class="padding50px">
    <%= link_to 'New Setting', new_setting_path, class: 'btn btn-primary' %>
    <%= link_to 'Back', root_path, class: 'btn btn-default' %>
    <table class="table margintop20px">
      <tr>
          <th>Object Key</th>
          <th>Object Value</th>
          <th>Action</th>
      </tr>
      <% @settings.each do |setting| %>
        <tr>
          <td>
            <%= setting.object_key %>
          </td>
          <td>
            <%= setting.object_value %>
          </td>
          <td><%= link_to 'Edit', edit_setting_path(setting.id) %> | <%= link_to 'Delete', destroy_setting_path(setting.id), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="6" class="center-position"><%= paginate @settings %></td>
      </tr>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AcmeTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/flash_message' %>
<%= yield %>

</body>
</html>

app/views/shared/_flash_message.html.erb
<% if flash[:notice].present? %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% elsif flash[:alert].present? %>
  <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
<% end %>